Repository edicoehf/Utkeyrslukerfi, pull requests merged in 2021-03, with the labels that each got.

#74 finished update user
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/Exceptions/InvalidLoginException.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/Exceptions/NotFoundException.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/DeliveryRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/UserRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Implementations/UserService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Interfaces/IUserService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Controllers/UserController.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Middlewares/ErrorHandlingMiddleware.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Utkeyrslukerfi.API.csproj
Labels: requirement

#89 Ermir
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/DTOs/DeliveryDTO.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/Entities/Delivery.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/InputModels/DeliveryInputModel.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/InputModels/VehicleInputModel.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/AddressRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/DeliveryRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/VehicleRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Interfaces/IAddressRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Interfaces/IVehicleRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Implementations/AddressService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Implementations/PackageService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Implementations/VehicleService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Interfaces/IAddressService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Interfaces/IVehicleService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Controllers/AddressController.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Controllers/VehicleController.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Startup.cs
Labels: requirement

#128 Ermir
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Helpers/HashingHelpers.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/UserRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Utkeyrslukerfi.API.Repositories.csproj
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Controllers/AddressController.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Controllers/DeliveryController.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Controllers/PackageController.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Controllers/UserController.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Controllers/VehicleController.cs
Labels: requirement

#130 Added Package, fixed the URI for packages as well
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/InputModels/PackageInputModel.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/PackageRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Interfaces/IPackageRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Implementations/PackageService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Interfaces/IPackageService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Controllers/PackageController.cs
Labels: easy

#137 Added Header and Container in Frontend and
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/TokenRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Middlewares/JwtAuthenticationMiddleware.cs
  Web/utkeyrslukerfi-web/package-lock.json
  Web/utkeyrslukerfi-web/src/App.css
  Web/utkeyrslukerfi-web/src/App.js
  Web/utkeyrslukerfi-web/src/components/Container/index.jsx
  Web/utkeyrslukerfi-web/src/components/Navbar/index.jsx
  Web/utkeyrslukerfi-web/src/constants/index.jsx
  Web/utkeyrslukerfi-web/src/styles/main.css
  Web/utkeyrslukerfi-web/src/styles/navbar.css
Labels: bug

#176 Ermir
  Web/utkeyrslukerfi-web/package-lock.json
  Web/utkeyrslukerfi-web/package.json
  Web/utkeyrslukerfi-web/src/App.js
  Web/utkeyrslukerfi-web/src/actions/deliveriesActions.jsx
  Web/utkeyrslukerfi-web/src/actions/deliveryActions.jsx
  Web/utkeyrslukerfi-web/src/components/Container/index.jsx
  Web/utkeyrslukerfi-web/src/components/Delivery/index.jsx
  Web/utkeyrslukerfi-web/src/components/NavLinks/index.jsx
  Web/utkeyrslukerfi-web/src/components/Navbar/index.jsx
  Web/utkeyrslukerfi-web/src/constants/index.jsx
  Web/utkeyrslukerfi-web/src/index.js
  Web/utkeyrslukerfi-web/src/reducers/deliveriesReducer.jsx
  Web/utkeyrslukerfi-web/src/reducers/deliveryReducer.jsx
  Web/utkeyrslukerfi-web/src/reducers/index.jsx
  Web/utkeyrslukerfi-web/src/services/deliveryService.jsx
  Web/utkeyrslukerfi-web/src/styles/navbar.css
  Web/utkeyrslukerfi-web/src/views/Deliveries/index.jsx
  Web/utkeyrslukerfi-web/src/views/NotFound/index.jsx
  Web/utkeyrslukerfi-web/src/views/Users/index.jsx
Labels: bug, requirement

#178 Fixing error, a cannot be <a> descendant of <a> and translating
  Web/utkeyrslukerfi-web/src/components/NavLinks/index.jsx
  Web/utkeyrslukerfi-web/src/views/Deliveries/index.jsx
  Web/utkeyrslukerfi-web/src/views/UpdatePasswordForm/index.jsx
Labels: bug

#179 Fixing small bug, create under id route for users
  Web/utkeyrslukerfi-web/src/App.js
Labels: bug

#191 Ermir
  .github/workflows/azure-pipelines.yml
  Web/utkeyrslukerfi-web/src/components/Delivery/index.jsx
Labels: bug, moderate, requirement
