Repository edicoehf/Utkeyrslukerfi, pull requests merged in 2021-05, with the labels that each got.

#256 Ermir
  Backend/Tests/UnitTestDeliveryRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/DTOs/VehicleDTO.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/InputModels/DeliveryInputModel.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/InputModels/VehicleInputModel.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/DeliveryRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/VehicleRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Interfaces/IVehicleRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Implementations/VehicleService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Services/Interfaces/IVehicleService.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Controllers/VehicleController.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Mappings/MappingProfile.cs
  Handheld/UtkeyrslukerfiHandheld/package-lock.json
  Handheld/UtkeyrslukerfiHandheld/package.json
  Handheld/UtkeyrslukerfiHandheld/src/views/DetailsScreen/index.js
  Web/utkeyrslukerfi-web/package-lock.json
  Web/utkeyrslukerfi-web/src/actions/vehiclesActions.jsx
  Web/utkeyrslukerfi-web/src/components/Delivery/index.jsx
  Web/utkeyrslukerfi-web/src/constants/index.jsx
  Web/utkeyrslukerfi-web/src/reducers/index.jsx
  Web/utkeyrslukerfi-web/src/reducers/vehiclesReducer.jsx
  Web/utkeyrslukerfi-web/src/services/vehicleService.jsx
  Web/utkeyrslukerfi-web/src/views/Deliveries/index.jsx
Labels: challenging, requirement

#261 Users filter
  Web/utkeyrslukerfi-web/package-lock.json
  Web/utkeyrslukerfi-web/package.json
  Web/utkeyrslukerfi-web/src/actions/userActions.jsx
  Web/utkeyrslukerfi-web/src/components/Delivery/index.jsx
  Web/utkeyrslukerfi-web/src/components/UserFilterModal/index.jsx
  Web/utkeyrslukerfi-web/src/constants/index.jsx
  Web/utkeyrslukerfi-web/src/reducers/vehiclesReducer.jsx
  Web/utkeyrslukerfi-web/src/services/vehicleService.jsx
  Web/utkeyrslukerfi-web/src/styles/users.css
  Web/utkeyrslukerfi-web/src/views/Users/index.jsx
Labels: moderate

#265 Added so backend returns date
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/DTOs/DeliveryDTO.cs
Labels: easy

#278 Fixing bug in backend, no mapper for Signoff entity and DTO
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/DTOs/DeliveryDTO.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/DTOs/SignOffDTO.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/FetchDataRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Mappings/MappingProfile.cs
Labels: bug

#270 Ermir
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Models/Entities/Vehicle.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/AddressRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/DeliveryRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/TokenRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Implementations/VehicleRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API.Repositories/Interfaces/IVehicleRepository.cs
  Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/Middlewares/ErrorHandlingMiddleware.cs
  Handheld/UtkeyrslukerfiHandheld/package-lock.json
  Handheld/UtkeyrslukerfiHandheld/package.json
  Handheld/UtkeyrslukerfiHandheld/src/components/BarcodeForm/index.js
  Handheld/UtkeyrslukerfiHandheld/src/components/DeliveryTable/index.js
  Handheld/UtkeyrslukerfiHandheld/src/components/Login/index.js
  Handheld/UtkeyrslukerfiHandheld/src/components/ProductTable/index.js
  Handheld/UtkeyrslukerfiHandheld/src/constants/index.js
  Handheld/UtkeyrslukerfiHandheld/src/routes/index.js
  Handheld/UtkeyrslukerfiHandheld/src/styles/barcodeForm.js
  Handheld/UtkeyrslukerfiHandheld/src/styles/basicButton.js
  Handheld/UtkeyrslukerfiHandheld/src/styles/deliveryTable.js
  Handheld/UtkeyrslukerfiHandheld/src/styles/detailPageStyles.js
  Handheld/UtkeyrslukerfiHandheld/src/styles/listScreenStyles.js
  Handheld/UtkeyrslukerfiHandheld/src/styles/loginStyles.js
  Handheld/UtkeyrslukerfiHandheld/src/styles/productTable.js
  Handheld/UtkeyrslukerfiHandheld/src/styles/searchPageStyles.js
  Handheld/UtkeyrslukerfiHandheld/src/views/DetailsScreen/index.js
  Handheld/UtkeyrslukerfiHandheld/src/views/ListScreen/index.js
  Handheld/UtkeyrslukerfiHandheld/src/views/SearchScreen/index.js
  Web/utkeyrslukerfi-web/src/components/Delivery/index.jsx
  Web/utkeyrslukerfi-web/src/constants/index.jsx
Labels: easy
